// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-recent-draws.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_draws_default = defineTool({
  name: "list_recent_draws",
  title: "Listar sorteios recentes",
  description: "Retorna os sorteios oficiais mais recentes de uma loteria (Mega-Sena, Lotof\xE1cil, Quina, Lotomania, etc.) com concurso, data e dezenas sorteadas.",
  inputSchema: {
    lottery_id: z.string().min(1).describe("Identificador da loteria, ex.: 'lotofacil', 'megasena', 'quina', 'lotomania'."),
    limit: z.number().int().min(1).max(50).default(10).describe("Quantos sorteios retornar (1\u201350).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lottery_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("lottery_draws").select("concurso, draw_date, numbers").eq("lottery_id", lottery_id).order("concurso", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { lottery_id, draws: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/top-numbers.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var top_numbers_default = defineTool2({
  name: "top_numbers",
  title: "Dezenas mais frequentes",
  description: "Retorna as dezenas mais frequentes de uma loteria com base em todo o hist\xF3rico oficial j\xE1 sincronizado.",
  inputSchema: {
    lottery_id: z2.string().min(1).describe("Identificador da loteria, ex.: 'lotofacil', 'megasena'."),
    limit: z2.number().int().min(1).max(50).default(10).describe("Quantas dezenas retornar.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lottery_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).rpc("get_top_numbers", {
      p_lottery_id: lottery_id,
      p_limit: limit
    });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { lottery_id, top: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-saved-bets.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_saved_bets_default = defineTool3({
  name: "list_my_saved_bets",
  title: "Minhas apostas salvas",
  description: "Lista as apostas salvas do usu\xE1rio autenticado no Titan Loterias, opcionalmente filtrando por loteria.",
  inputSchema: {
    lottery_id: z3.string().nullable().default(null).describe("Filtro opcional por loteria (ex.: 'lotofacil'). null para todas."),
    limit: z3.number().int().min(1).max(100).default(20).describe("M\xE1ximo de apostas a retornar.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lottery_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let query = supabase.from("saved_bets").select("id, lottery_id, numbers, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (lottery_id) query = query.eq("lottery_id", lottery_id);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { bets: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cghydrrvebnkdugdlcia";
var mcp_default = defineMcp({
  name: "titan-loterias-mcp",
  title: "Titan Loterias",
  version: "0.1.0",
  instructions: "Ferramentas do Titan Loterias: consulte sorteios oficiais recentes, dezenas mais frequentes e as apostas salvas do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_recent_draws_default, top_numbers_default, list_saved_bets_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
